spring:
  application:
    name: ms-barbershop
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/barbershopDb
    username: postgres
    password: 123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      - hibernate.dialect: org.hibernate.dialect.PostgreSQL9Dialect
  liquibase:
    enabled: false
server:
  port: 8080